import type { BloomEntry } from "./bloom";

export const bloomEntries = [
  {
    id: "camellia",
    name: "Camellias",
    emoji: "🌺",
    pixelArt: "/assets/v2/blooms/camellia.png",
    startMonth: 1,
    startDay: 15,
    endMonth: 3,
    endDay: 15,
    place: "Izu Oshima",
    region: "Tokyo",
    sourceUrl: "https://www.japan.travel/en/spot/2180/",
  },
  {
    id: "plum",
    name: "Plum blossoms",
    emoji: "🌸",
    pixelArt: "/assets/v2/blooms/plum.png",
    startMonth: 2,
    startDay: 20,
    endMonth: 3,
    endDay: 25,
    place: "Kairakuen Garden",
    region: "Ibaraki",
    sourceUrl: "https://www.japan.travel/en/spot/1466/",
  },
  {
    id: "sakura",
    name: "Cherry blossoms",
    emoji: "🌸",
    pixelArt: "/assets/v2/blooms/sakura.png",
    startMonth: 3,
    startDay: 20,
    endMonth: 4,
    endDay: 10,
    place: "Tokyo",
    region: "Kanto",
    sourceUrl: "https://www.japan.travel/en/see-and-do/flowers/",
  },
  {
    id: "wisteria",
    name: "Wisteria",
    emoji: "🪻",
    pixelArt: "/assets/v2/blooms/wisteria.png",
    startMonth: 4,
    startDay: 15,
    endMonth: 5,
    endDay: 15,
    place: "Ashikaga Flower Park",
    region: "Tochigi",
    sourceUrl: "https://www.japan.travel/en/spot/1473/",
  },
  {
    id: "hydrangea",
    name: "Hydrangeas",
    emoji: "🪻",
    pixelArt: "/assets/v2/blooms/hydrangea.png",
    startMonth: 6,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    place: "Hasedera Temple",
    region: "Kamakura",
    sourceUrl: "https://www.japan.travel/en/see-and-do/flowers/",
  },
  {
    id: "lotus",
    name: "Ancient lotuses",
    emoji: "🪷",
    pixelArt: "/assets/v2/blooms/lotus.png",
    startMonth: 6,
    startDay: 25,
    endMonth: 8,
    endDay: 5,
    place: "Ancient Lotus Park",
    region: "Gyoda, Saitama",
    sourceUrl: "https://www.japan.travel/en/spot/2082/",
  },
  {
    id: "sunflower",
    name: "Sunflowers",
    emoji: "🌻",
    pixelArt: "/assets/v2/blooms/sunflower.png",
    startMonth: 7,
    startDay: 27,
    endMonth: 8,
    endDay: 15,
    place: "Hokuryu Sunflower Village",
    region: "Hokkaido",
    sourceUrl: "https://www.japan.travel/en/spot/1882/",
  },
  {
    id: "cosmos",
    name: "Cosmos",
    emoji: "🌼",
    pixelArt: "/assets/v2/blooms/cosmos.png",
    startMonth: 9,
    startDay: 20,
    endMonth: 10,
    endDay: 20,
    place: "Hitachi Seaside Park",
    region: "Ibaraki",
    sourceUrl: "https://www.japan.travel/en/see-and-do/flowers/",
  },
  {
    id: "chrysanthemum",
    name: "Chrysanthemums",
    emoji: "🏵️",
    pixelArt: "/assets/v2/blooms/chrysanthemum.png",
    startMonth: 11,
    startDay: 1,
    endMonth: 11,
    endDay: 15,
    place: "Shinjuku Gyoen",
    region: "Tokyo",
    sourceUrl: "https://www.env.go.jp/garden/shinjukugyoen/english/",
  },
] as const satisfies readonly BloomEntry[];
